name: CI

on: 
  push:
    branches:
      - 'docker'

jobs:
 R_latest:
   name: Test on latest
   runs-on: windows-latest
   #container: 
   #   image: cr.microsoft.com/windows/servercore:ltsc2019
   steps:
    - name: run docker
      run: docker run mcr.microsoft.com/windows/servercore:ltsc2019
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget restore
      run: nuget restore DotnetCoreConsole\DotnetCoreConsole.sln
    - name: msbuild
      run: .\scripts\buildMaster.ps1
      shell: powershell
   
    
