name: CI

on: 
  push:
    branches:
      - 'docker'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: check container
      uses: docker://mcr.microsoft.com/windows/servercore:ltsc2019
      with:
        args: echo "This is from the container"
    
