name: CI

on: 
  push:
    branches:
      - 'docker'

jobs:
 R_latest:
   name: Test on latest
   runs-on: windows-latest
   #container: 
   #   image: cr.microsoft.com/windows/servercore:ltsc2019
   steps:
    #- name: run docker
    #  run: docker run mcr.microsoft.com/windows/servercore:ltsc2019
    - uses: actions/checkout@v1
    #- name: Setup Nuget.exe
    #  uses: warrenbuckley/Setup-Nuget@v1
    #- name: Nuget restore
    #  run: nuget restore DotnetCoreConsole\DotnetCoreConsole.sln
    #- name: msbuild
    #  run: .\scripts\buildMaster.ps1
    #  shell: powershell
    - name: env vars GITHUB_WORKSPACE
      run: Write-Host "${env:GITHUB_WORKSPACE}"
      shell: powershell
    - name: env vars GITHUB_REPOSITORY
      run: Write-Host "${env:GITHUB_REPOSITORY}"
      shell: powershell
    - name: env vars GITHUB_SHA
      run: Write-Host "${env:GITHUB_SHA}"
      shell: powershell
    - name: ssh
      run: ls ~\.ssh\
      shell: powershell
   
    
