name: CI

on: 
  push:
    branches:
      - 'docker'

jobs:
 R_latest:
   name: Test on latest
   runs-on: windows-latest
   #container: 
   #   image: cr.microsoft.com/windows/servercore:ltsc2019
   steps:
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: mdsol-rave-containers.jfrog.io # default: index.docker.io
        username: rave-ci
        password: AKCp5e3Kxf9ygMr8jfSRVwWr7iWK6vBDzMr9BXMecRzs7zqywEkM7qMtdKJfEn3eWVH2h9UvD
    - name: pull docker
      run: docker run -d mdsol-rave-containers.jfrog.io/rave-containers/ci/buildtools2019/latest powershell;
      shell: powershell
   
    
