name: CI

on: 
  push:
    branches:
      - 'docker'

jobs:
 R_latest:
   name: Test on latest
   runs-on: windows-latest
   #container: 
   #   image: cr.microsoft.com/windows/servercore:ltsc2019
   steps:
    - name: login docker
      run: docker login mdsol-rave-containers.jfrog.io -u rave-ci -p '${{ secrets.ARTIFACTORY_TOKEN}}'
      shell: powershell
    - name: pull docker
      run: docker run -d mdsol-rave-containers.jfrog.io/rave-containers/ci/buildtools2019/latest powershell;
      shell: powershell
   
    
